all:
	g++ main.cpp utils.cpp ProgramArguments.cpp multiplier.cpp conv.cpp strassen.cpp strassenSeuil.cpp -o main.out

# serie_number = 11
# mat1_number = 1
# mat2_number = 2
# matrices_path = serie$(serie_number)/ex_$(serie_number).$(mat1_number) serie$(serie_number)/ex_$(serie_number).$(mat2_number)

clean:
	rm *out

# utils:
# 	g++ utils.cpp -o utils.out

# conv:
# 	g++ conv.cpp utils.cpp ProgramArguments.cpp multiplier.cpp -o conv.out
# 	./conv.out $(matrices_path) -t

# strassen:
# 	g++ strassen.cpp conv.cpp utils.cpp ProgramArguments.cpp multiplier.cpp -o strassen.out
# 	./strassen.out $(matrices_path) -t
